### ISSUE TITLE
Moving icons

### ISSUE THREAD

**Issue by megatech1966** [AnthoPakPak/PanCake#3]
Moving icons causes respring in to safe mode. iPhone 12 Pro Max. iOS 14.5.1 unc0ver 7.0.2 
Pancake 2.1

**Comment by AnthoPakPak** [comment]
Hey, it's probably a conflict with another tweak. But still, if it's happening I suppose you have enabled "Inject into SpringBoard" option in PanCake settings. Can you try disabling it to see if it helps? Most people doesn't need this option On.

**Comment by megatech1966** [comment]
That worked
