### ISSUE TITLE
Spotify new versions fix

### ISSUE THREAD

**Issue by Hamzabdx** [AnthoPakPak/PanCake#6]
Please fix spotify issue with newer versions where the tweak still works but causes bug where you cant swipe down/up anymore in many places inside the app including settings/playlists etc

**Comment by AnthoPakPak** [comment]
Yeah I've had the issue too, Spotify now needs to be blacklisted (either from PanCake settings if you're on rootful jailbreak, or using Choicy if you're on a rootless jailbreak).

**Comment by Hamzabdx** [comment]
I know thats what ive done but cant you add a fix for that app specifically it would be appreciated
